name: Build and deploy Node.js app to Azure Web App - sw-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_ENV: production
  DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Asegúrate de tener este secret en GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'  # Cachea dependencias para mayor velocidad

      - name: Install dependencies
        run: npm ci  # Más rápido y confiable que npm install

      - name: Build application
        run: npm run build

      - name: Run Prisma generate
        run: npx prisma generate  # Genera el cliente de Prisma

      - name: Create optimized deployment package
        run: |
          # Excluye archivos innecesarios (reduce el ZIP en ~90%)
          zip -r release.zip \
            dist/* \
            package.json \
            package-lock.json \
            prisma/schema.prisma \
            node_modules/.prisma \
            -x '*.git*' '*.md' 'tests/*'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip -d deployment-folder

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B19C05B3891848DBB33FE358AF313D1E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_784C0832E2644202B03131EF87E2386F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B388094482B24231B861F05E407BE9C7 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sw-api'
          slot-name: 'Production'
          package: deployment-folder  # Usa solo la carpeta optimizada
